version: 2
registries:
  npm-registry-registry-yarnpkg-com:
    type: npm-registry
    url: https://registry.yarnpkg.com
    token: "${{secrets.NPM_REGISTRY_REGISTRY_YARNPKG_COM_TOKEN}}"
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "01:00"
    timezone: America/New_York
  open-pull-requests-limit: 99
  ignore: []
  registries:
  - npm-registry-registry-yarnpkg-com
  - npm-registry-registry-npmjs-org
