image: docker.gamechanger.io/nodejs/10

stages:
    - setup
    - test
    - build
    - deploy

install:
    stage: setup
    script:
        - yarn install
    interruptible: true
    artifacts:
        name: 'node-modules-$CI_COMMIT_REF_NAME'
        expire_in: 1 hour
        paths:
            - node_modules/
            - lib/
    only:
        refs:
            - branches
            - tags

lint:
    stage: test
    script:
        - yarn lint
    interruptible: true
    only:
        refs:
            - branches
            - tags

test:
    stage: test
    script:
        - yarn test
    only:
        refs:
            - branches
            - tags

publish:
    stage: deploy
    script:
        - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
        - npm publish
    only:
        - /\d+\.\d+\.\d+/
